# Generated by Django 4.1.2 on 2022-10-26 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0004_alter_room_amenities_alter_room_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="price",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="rooms",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="toilets",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
