# Generated by Django 4.1.2 on 2022-10-18 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
        ("experiences", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="categories.category",
            ),
        ),
        migrations.AddField(
            model_name="experience",
            name="city",
            field=models.CharField(default="서울", max_length=80),
        ),
        migrations.AddField(
            model_name="experience",
            name="perks",
            field=models.ManyToManyField(to="experiences.perk"),
        ),
        migrations.AlterField(
            model_name="experience",
            name="country",
            field=models.CharField(default="한국", max_length=50),
        ),
        migrations.RemoveField(
            model_name="experience",
            name="description",
        ),
        migrations.AddField(
            model_name="experience",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
